version: '3.7'

services:

  mysql:
    image: mysql:8-debian
    platform: linux/amd64
    restart: unless-stopped
    container_name: docker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testDB
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql"
