version: '3.7'

services:

  postgres:
    image: postgres:13-alpine
    platform: linux/amd64
    restart: unless-stopped
    container_name: docker-postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testDB
      POSTGRES_USER: root
    ports:
      - "5432:5432"
    volumes:
      - "./docker/postgres/dump.sql:/docker-entrypoint-initdb.d/dump.sql"
